# Generated by Django 2.2.11 on 2020-03-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="frequency",
            field=models.FloatField(blank=True, null=True, verbose_name="Frequency"),
        ),
        migrations.AlterField(
            model_name="note",
            name="name",
            field=models.CharField(max_length=3, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="scale",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="scale",
            name="notes",
            field=models.ManyToManyField(
                related_name="scales",
                related_query_name="scales",
                to="core.Note",
                verbose_name="Notes",
            ),
        ),
    ]
