# Generated by Django 2.2.11 on 2020-03-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20200315_1657"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="octave",
            field=models.IntegerField(default=0, verbose_name="Octave number"),
            preserve_default=False,
        ),
    ]
