# Generated by Django 2.2.11 on 2020-03-15 18:43

from django.db import migrations, models
import music_generator.core.enums


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_note_octave"),
    ]

    operations = [
        migrations.RemoveField(model_name="note", name="octave",),
        migrations.AddField(
            model_name="note",
            name="index",
            field=models.IntegerField(default=0, unique=True, verbose_name="Index"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="is_sharp",
            field=models.BooleanField(default=False, verbose_name="Is sharp"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scale",
            name="scale_type",
            field=models.CharField(
                choices=[
                    (music_generator.core.enums.ScaleTypes("chromatic"), "chromatic"),
                    (music_generator.core.enums.ScaleTypes("octatonic"), "octatonic"),
                    (music_generator.core.enums.ScaleTypes("heptatonic"), "heptatonic"),
                    (music_generator.core.enums.ScaleTypes("hexatonic"), "hexatonic"),
                    (music_generator.core.enums.ScaleTypes("pentatonic"), "pentatonic"),
                    (music_generator.core.enums.ScaleTypes("tetratonic"), "tetratonic"),
                    (music_generator.core.enums.ScaleTypes("monotonic"), "monotonic"),
                ],
                default="",
                max_length=16,
                verbose_name="Type",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="note",
            name="name",
            field=models.CharField(max_length=3, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="scale",
            name="name",
            field=models.CharField(max_length=64, unique=True, verbose_name="Name"),
        ),
    ]
