# Generated by Django 2.2.11 on 2020-03-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_note_octave"),
    ]

    operations = []
