# Generated by Django 2.2.11 on 2020-03-15 18:49

from django.db import migrations, models
import music_generator.core.enums


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20200315_1843"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scale",
            name="scale_type",
            field=models.CharField(
                choices=[
                    (music_generator.core.enums.ScaleTypes("chromatic"), "chromatic"),
                    (music_generator.core.enums.ScaleTypes("octatonic"), "octatonic"),
                    (music_generator.core.enums.ScaleTypes("heptatonic"), "heptatonic"),
                    (music_generator.core.enums.ScaleTypes("hexatonic"), "hexatonic"),
                    (music_generator.core.enums.ScaleTypes("pentatonic"), "pentatonic"),
                    (music_generator.core.enums.ScaleTypes("tetratonic"), "tetratonic"),
                    (music_generator.core.enums.ScaleTypes("monotonic"), "monotonic"),
                ],
                max_length=32,
                verbose_name="Type",
            ),
        ),
    ]
